### ISSUE TITLE
Am getting an error if I deploy this app in my elastic beanstalk

### ISSUE THREAD

**Issue by mwaaas** [circleci/docker-hello#4]
This is the error

Digest: sha256:1be5fd347507f05e093dbfe0f1ee1a26d8a50d734289dbc8e10262d80f4dd30c
sanity-check: "/home/ubuntu/.awssecret": file is missing.  (Format: AccessKeyID\nSecretAccessKey\n)
s3: unknown command

**Comment by bellkev** [comment]
Make sure to add a requirements.txt like the one in this repo so that pip will automatically install the correct awscli version.

**Comment by mwaaas** [comment]
I have added the requirement.txt in the repo but it still fails with the error below and then I can't see any pip install in the circle build

	The link with 'rds-' on the front will list all the parameter shortcuts
--application-name: mispelled meta parameter?

./deploy.sh $CIRCLE_SHA1 returned exit code 2

--environment-name: mispelled meta parameter? Action failed: ./deploy.sh $CIRCLE_SHA1

**Comment by mwaaas** [comment]
I have figured it out. adding the following solved the problem 

dependencies:
  pre:
    - sudo pip install awscli==1.3.24
